version: "3.3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - login
    environment:
      - DB_HOST=db
      - DB_NAME=maindb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DB_PORT=3306
      - LOGIN_HOST=login
      - LOGIN_PORT=8000
    volumes:
      - ./build/libs/:/usr/local/tomcat/webapps/

  db:
    image: mysql:8.0-debian
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=maindb
      - MYSQL_ROOT_PASSWORD=thisisnotsafe

volumes:
  mysql-data:
## volumes:
##   login-db-data:
