version: "3.3"

services:

  db:
    image: mysql:8.0-debian
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=maindb
      - MYSQL_ROOT_PASSWORD=thisisnotsafe

volumes:
  mysql-data:
## volumes:
##   login-db-data:
